spring.application.name=conglaturator
spring.datasource.url=jdbc:postgresql://localhost:5432/birthdays
spring.datasource.username=postgres
spring.datasource.password=593721
spring.jpa.hibernate.ddl-auto=update
server.port=3000
